/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerGuidanceRouteImport } from './routes/career-guidance'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGuidanceRoute = CareerGuidanceRouteImport.update({
  id: '/career-guidance',
  path: '/career-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/contact': typeof ContactRoute
  '/programs': typeof ProgramsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/contact': typeof ContactRoute
  '/programs': typeof ProgramsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/contact': typeof ContactRoute
  '/programs': typeof ProgramsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/career-guidance'
    | '/contact'
    | '/programs'
    | '/success-stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/career-guidance'
    | '/contact'
    | '/programs'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/career-guidance'
    | '/contact'
    | '/programs'
    | '/success-stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CareerGuidanceRoute: typeof CareerGuidanceRoute
  ContactRoute: typeof ContactRoute
  ProgramsRoute: typeof ProgramsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guidance': {
      id: '/career-guidance'
      path: '/career-guidance'
      fullPath: '/career-guidance'
      preLoaderRoute: typeof CareerGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  CareerGuidanceRoute: CareerGuidanceRoute,
  ContactRoute: ContactRoute,
  ProgramsRoute: ProgramsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
